### ISSUE TITLE
error on server shutdown

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/dIRCBot#6]
Just found this error in the console after using  `/restart` and wanted you to let you know.

```
[11:12:59 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled 
[11:12:59 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:403) 
[11:12:59 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:126) 
[11:12:59 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:122) 
[11:12:59 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:105) 
[11:12:59 WARN]: 	at org.mcmonkey.dIRCBot.IRCServerHolder.run(IRCServerHolder.java:100) 
```

**Comment by mcmonkey4eva** [comment]
I'm not sure how or why, but you're running a version of dIRCBot that isn't the only release on the CI.
